version: '3.8'

services:
  # FastAPI web application service
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 # Use a common port like 8000 for development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase # Update with your DB credentials
      - REDIS_URL=redis://redis:6379/0 # Redis connection URL

  # PostgreSQL database service
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase  # Database name
      - POSTGRES_USER=user  # Database user
      - POSTGRES_PASSWORD=password  # Database password

  # Redis service for Celery broker and caching
  redis:
    image: redis:latest

  # Celery worker service for processing background tasks
  worker:
    build: .
    command: celery -A app.background_tasks.celery_worker worker -l info -P solo # Command to run Celery worker
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db # Worker might need DB access
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase # Update with your DB credentials
      - REDIS_URL=redis://redis:6379/0 # Redis connection URL

volumes:
  postgres_data:
    # Volume to persist PostgreSQL data